name: "testapi-development"
services:

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      target: development
    container_name: nginx-nebalus-api
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/public:ro
    depends_on:
      - php-fpm
    networks:
      - public-net

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-nebalus-api
    ports:
      - '8080:80'
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - private-net
      - public-net

  # INTERN PORT: 9000
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      target: development
    container_name: nebalus-api
    user: '1001:1001' # Default User ID
    volumes:
      - ./:/var/www:rw
    environment:
      APP_ENV: "development"
      ERROR_LOGLEVEL: "Warning"
      JWT_SECRET: "Fm4}hopm2JGs]#h:!EE1)w0#?b9-8abjGg6PCuk.-j2R7w8OIqSO3D'ev@2]h!"
      JWT_NORMAL_EXPIRATION_TIME: 86400
      JWT_EXTENDED_EXPIRATION_TIME: 604800
      ACCESS_CONTROL_ALLOW_ORIGIN: "*"
      MYSQL_HOST: "mysql"
      MYSQL_PORT: "3306"
      MYSQL_DATABASE: "main"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "12345"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    depends_on:
      - mysql
#      - redis
    networks:
      - public-net
      - private-net

  # INTERN PORT: 3306
  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
      target: base
    container_name: mysql-nebalus-api
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_DATABASE: "main"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "12345"
    volumes:
      - /var/lib/mysql
    networks:
      - private-net

  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
      target: base
    container_name: redis-nebalus-api
#    environment:
#      REDIS_PASSWORD: "12345"
#    command: [ "redis-server", "--requirepass", "$$REDIS_PASSWORD" ]
    command: [ "redis-server" ]
    networks:
      - private-net

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter-nebalus-api
    environment:
      REDIS_ADDR: "redis:6379"
#      REDIS_PASSWORD: "12345"
    networks:
      - private-net

  prometheus:
    build:
      context: .
      dockerfile: docker/prometheus/Dockerfile
      target: base
    container_name: prometheus-nebalus-api
    ports:
      - '9393:9090'
    networks:
      - private-net

  grafana:
    build:
      context: .
      dockerfile: docker/grafana/Dockerfile
      target: base
    container_name: grafana-nebalus-api
    ports:
      - '3031:3000'
    networks:
      - public-net

#  elasticsearch:
#    image: elasticsearch:8.17.0
#    container_name: elasticsearch-nebalus-api
#    environment:
#      - discovery.type=single-node
#      - ELASTIC_PASSWORD=12345
#      - xpack.security.enabled=true
#      - xpack.license.self_generated.type=basic
#      - ES_JAVA_OPTS=-Xms512m -Xmx512m
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    ports:
#      - '9200:9200'
#    networks:
#      - public-net
#
#  kibana:
#    image: kibana:8.17.0
#    container_name: kibana-nebalus-api
#    environment:
#      - XPACK_SECURITY_ENABLED=true
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#      - ELASTICSEARCH_USERNAME=kibana_system
#      - ELASTICSEARCH_PASSWORD=12345
#    ports:
#      - '5601:5601'
#    networks:
#      - public-net

networks:
  public-net:
    name: public-net
  private-net:
    name: private-net
