version: "3.9"

name: "testapi-production"
services:

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      target: production
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/public:ro
    depends_on:
      - php-fpm
      - mysql-db

  # INTERN PORT: 9000
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      target: production
    volumes:
      - ./:/var/www:rw
    environment:
      APP_ENV: "production"
    depends_on:
      - mysql-db

  # INTERN PORT: 3306
  mysql-db:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
      target: base
    environment:
      MYSQL_ROOT_PASSWORD: NUTELLA
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12346
      MYSQL_DATABASE: todo
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
