version: "3.9"

name: "testapi-development"
services:

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      target: development
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/public:ro
    depends_on:
      - php-fpm
    networks:
      - public-net

  phpmyadmin:
    image: phpmyadmin
    ports:
      - '8080:80'
    environment:
      - PMA_HOST=mysql
    networks:
      - db-net
      - public-net

  # INTERN PORT: 9000
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      target: development
    volumes:
      - ./:/var/www:rw
    environment:
      APP_ENV: "development"
      JWT_SECRET: "vtV!hGCp|uXB+-R-oO5j@H|4xA[0,T-x!Q*6S,P53\;sikb|#Kk|QM=c70[edDP7m#}Fg4veq6ActKb.mhE.-S{k\0dCb0'.:E=!"
      MYSQL_HOST: "mysql:3306"
      MYSQL_DBNAME: "main"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "12346"
    depends_on:
      - mysql
    networks:
      - public-net
      - db-net

  # INTERN PORT: 3306
  mysql:
    hostname: "mysql"
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
      target: base
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "main"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "12346"
    volumes:
      - /var/lib/mysql
    networks:
      - db-net

networks:
  public-net:
    name: public-net
  db-net:
    name: db-net
