name: "testapi-production"
services:

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      target: production
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    networks:
      - public-net

  # INTERN PORT: 9000
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      target: production
    volumes:
      - /var/www/cache
    environment:
      APP_ENV: "production"
      ERROR_LOGLEVEL: "Warning"
      JWT_SECRET: "tVP1RJcLvBDCuyjUoDEX3BpmGCfz147VMbjDckjS2pjYzh6qm4qDsljzqZRXdKxSvPDO5XhhiH"
      JWT_NORMAL_EXPIRATION_TIME: 86400
      JWT_EXTENDED_EXPIRATION_TIME: 604800
      ACCESS_CONTROL_ALLOW_ORIGIN: "*"
      MYSQL_HOST: "mysql:3306"
      MYSQL_DATABASE: "main"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "7gmRdrz4E6"
    depends_on:
      - mysql
      - redis
    networks:
      - public-net
      - private-net

  # INTERN PORT: 3306
  mysql:
    hostname: "mysql"
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
      target: base
    environment:
      MYSQL_ROOT_PASSWORD: "%!28dnZY7%5U$Z"
      MYSQL_DATABASE: "main"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "7gmRdrz4E6"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - private-net

  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
      target: base
    networks:
      - private-net

volumes:
  mysql-data:

networks:
  public-net:
    name: public-net
  private-net:
    name: private-net