version: "3.9"

name: "testapi-production"
services:

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      target: production
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    networks:
      - public-net

  # INTERN PORT: 9000
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      target: production
    volumes:
      - /var/www/cache
    environment:
      APP_ENV: "production"
      ERROR_LOGLEVEL: "Warning"
      JWT_SECRET: "t]VP1RJcL){v+BDC?{uyjUoD}]EX3B(pmGCfz147VMbj@3:Dck-jS2P'pj,rYzh6q@m4q()Ds}:|ljzqZRXdKxSv{PDO5X{h]hiH"
      MYSQL_HOST: "mysql:3306"
      MYSQL_DBNAME: "main"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "&!7gmRdr&z4#E6"
    depends_on:
      - mysql
    networks:
      - public-net
      - database-net

  # INTERN PORT: 3306
  mysql:
    hostname: "mysql"
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
      target: base
    environment:
      MYSQL_ROOT_PASSWORD: "%!28dnZY7%5U$Z"
      MYSQL_DATABASE: "main"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "&!7gmRdr&z4#E6"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - database-net

volumes:
  mysql-data:

networks:
  public-net:
    name: public-net
  database-net:
    name: database-net