version: "3.9"

name: "testapi-development"
services:

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      target: development
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/public:ro
    depends_on:
      - php-fpm
    networks:
      - public-net

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - '8080:80'
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - private-net
      - public-net

  # INTERN PORT: 9000
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      target: development
    container_name: api
    user: '1000:1000' # Default User ID
    volumes:
      - ./:/var/www:rw
    environment:
      APP_ENV: "development"
      ERROR_LOGLEVEL: "Warning"
      JWT_SECRET: "vtV!hGCp|uXB+-R-oO5j@H|4xA[0,T-x!Q*6S,P53"
      MYSQL_HOST: "mysql:3306"
      MYSQL_DBNAME: "main"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "12345"
      ACCESS_CONTROL_ALLOW_ORIGIN: "*"
    depends_on:
      - mysql
    networks:
      - public-net
      - private-net

  # INTERN PORT: 3306
  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
      target: base
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_DATABASE: "main"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "12345"
    volumes:
      - /var/lib/mysql
    networks:
      - private-net

networks:
  public-net:
    name: public-net
  private-net:
    name: private-net
