name: Publish Docker Images to GHCR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image for nginx
        run: |
          docker buildx build --platform linux/amd64 \
            -t ghcr.io/nebalus/webbackend/nginx:dev \
            -f docker/nginx/Dockerfile \
            --cache-from=type=gha \
            --cache-to=type=gha,mode=max \
            --push \
            .

      - name: Build and push Docker image for php-fpm
        run: |
          docker buildx build --platform linux/amd64 \
            -t ghcr.io/nebalus/webbackend/api:dev \
            -f docker/php-fpm/Dockerfile \
            --cache-from=type=gha \
            --cache-to=type=gha,mode=max \
            --push \
            .

      - name: Build and push Docker image for redis
        run: |
          docker buildx build --platform linux/amd64 \
            -t ghcr.io/nebalus/webbackend/redis:dev \
            -f docker/redis/Dockerfile \
            --cache-from=type=gha \
            --cache-to=type=gha,mode=max \
            --push \
            .
